environment: test
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: ciaobella
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
  h2:
    console:
      enabled: true